Debug configuration for VSCode (launch.json) ============================================ Generalized slightly to be more portable between directories. But working directory is project-specific. Get python in data directory so the node programs invoked by maestro don't fail for lack of inputs.
Improved running under maestro.py
=================================
End JSON output with \n since without it I was getting nothing until
the whole run finished (admittedly only 2 reps).

Set json_logging outside and before simRuns() since some startup code at
the bottom runs before simRuns() executes and that startup code may fail.

Also output arguments since they weren't being set properly; earlier I showed
1000 iterations, even though 2 clearly requested.  I suspect the cause was
deleting positional arguments from the command string for run-sims in mc.js.
I restored them, and added optional arguments too.  Because of defaults, they
are all optional.

With old code the presence of previous output led to interactive input
about how to handle it; that's not possible in batch mode and I think
just hung the child program.  Now I fail in that case in batch (json)
mode UNLESS --overwrite is specified.   This new option, usable with or without --json,
causes the program to proceed and silently overwrite existing output.

Note --json is defined with boolean: true and no default, while the vscode/
copilot suggested type: 'boolean', default: false used for --overwrite.

I am not sure that boolean: true was necessary; I added it because the --json
wasn't sticking.  But the real cause was the sequence issue noted above.

maestro.py
==========
Add --json and --overwrite to the node invocation; the latter is hazardous.

Added comment to suppress spurious VSCode warning about r.stdout.

Add code to parse strings to JSON, including error handling for plain strings.

Added the wait at the end because without it I got

```
{'type': 'DONE', 'text': '  simulations completed in 6 minutes!'}
Done with status None.
Exception ignored in: <function Popen.__del__ at 0x000001C8D5C73CE0>
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1130, in __del__
    self._internal_poll(_deadstate=_maxsize)
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1575, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
```
I only saw that once and do not know if wait is any cure.  Maybe the
`for line in r.stdout` does a close at the end, and then delete tries
it again?

Help
====
(pyenv) PS C:\Users\rdboylan\Documents\KBD\MC_SELECT_06.02.2025> node $MYMC --help
mc.js [command]

Commands:
  mc.js init                                initialize MC system in current
                                            directory
  mc.js run-sims [iterations] [start]       run MC simulations
  [seed] [--json] [--overwrite]                                [aliases: run, r]

Options:
  --version       Show version number                                  [boolean]
  --python, --py        [string] [default: py probably only works on MS-Windows]
  --help          Show help                                            [boolean]

(pyenv) PS C:\Users\rdboylan\Documents\KBD\MC_SELECT_06.02.2025> node $MYMC run --help
mc.js run-sims [iterations] [start] [seed] [--json] [--overwrite]

run MC simulations

Positionals:
  iterations  Number of simulations to perform          [number] [default: 1000]
  start       Number of first simulation.  Simulations will range from start to
              start+iterations-1                           [number] [default: 0]
  seed        seed for random number generator.  Will be combined with
              simulation number.  If omitted random numbers will not be
              reproducible, may not be sufficiently independent across
              simulations, and may stall the simulation and other processes by
              exhausting system entropy.                                [number]

Options:
  --version       Show version number                                  [boolean]
  --python, --py        [string] [default: py probably only works on MS-Windows]
  --help          Show help                                            [boolean]
  --json          Format output using JSON, ordinarily for use by another
                  program.  All to stdout.  All objects have a type, one of
                  PROGRESS (simulation progress), SUMMARY (after all sims
                  complete), DETAIL (details of all simulations), DONE (very
                  last message), or ERR (error).  All have a text field with the
                  main message, and some have additional fields.  See code for
                  details.  Note that programs invoked by run-sims will still
                  generate non-JSON output on stdout and, possibly, stderr.
                                                                       [boolean]
  --overwrite     Overwrite existing results *without* notice.
                                                      [boolean] [default: false]

All numbers should be unsigned integers.