Fix double creation of directory for stemcell
While trying to make a minimal copy of a project I changed maestro.py to do a stemcell creation.

Initial attempts failed with

(pyenv) PS C:\Users\rdboylan\Documents\KBD\JUSTICE_MonteCarlo_8spk> python $MAESTRO
Traceback (most recent call last):
  File "C:\Users\rdboylan\Documents\KBD\mccli-parallel\bin\python\maestro.py", line 109, in <module>
    prepare(basics, stemcell="../Justice_Lite")
  File "C:\Users\rdboylan\Documents\KBD\mccli-parallel\bin\python\symphony\prepare.py", line 109, in prepare
    prepare_one("", basics)
  File "C:\Users\rdboylan\Documents\KBD\mccli-parallel\bin\python\symphony\prepare.py", line 60, in prepare_one
    shutil.copytree(basics.DATADIR, pproj, ignore=AFilter(basics))
  File "C:\Program Files\Python311\Lib\shutil.py", line 561, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\shutil.py", line 459, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '..\\Justice_Lite'

even when I ensured Justice_Lite was deleted before the run.

* debugging configuration modified for new circumstances
* prepare.py modified so only creates the directory once.

An alternate approach would be to invoke shutil.copytree  with
dirs_exist_ok=True.  I didn't do that because I don't want to risk
overwriting previous runs.

I'm not sure why this wasn't an issue before.

With the code in this commit the program runs to completion, though it seems to have copied some things it shouldn't have.
original project: 268.0 MB, 484 files
stemcell copy: 205.0 MB, 479 files (but one more folder!?)