Fixes #24
test_shared_prefix now passes.

One of the old tests continue to fail:

Running pytest with args: ['-p', 'vscode_pytest', '--rootdir=c:\\Users\\rdboylan\\Documents\\KBD\\mccli-justice', 'c:\\Users\\rdboylan\\Documents\\KBD\\mccli-justice\\py_tests\\test_monte.py::test_inp', 'c:\\Users\\rdboylan\\Documents\\KBD\\mccli-justice\\py_tests\\test_monte.py::test_effects', 'c:\\Users\\rdboylan\\Documents\\KBD\\mccli-justice\\py_tests\\test_monte.py::test_component', 'c:\\Users\\rdboylan\\Documents\\KBD\\mccli-justice\\py_tests\\test_monte.py::test_dat', 'c:\\Users\\rdboylan\\Documents\\KBD\\mccli-justice\\py_tests\\test_monte.py::test_beta', 'c:\\Users\\rdboylan\\Documents\\KBD\\mccli-justice\\py_tests\\test_sum_results.py::test_shared_prefix']
============================= test session starts =============================
platform win32 -- Python 3.11.5, pytest-8.4.2, pluggy-1.6.0
rootdir: c:\Users\rdboylan\Documents\KBD\mccli-justice
plugins: cov-7.0.0
collected 6 items

py_tests\test_monte.py F....                                             [ 83%]
py_tests\test_sum_results.py .                                           [100%]

================================== FAILURES ===================================
__________________________________ test_inp ___________________________________

    def test_inp():
        # currently mostly used to see if montecarlo module loaded
        # it fails because input files are missing
>       inp = InpFile(str(rootDir / "Mod92_MC-setup_Working-example" / "i25"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

py_tests\test_monte.py:44:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bin\python\montecarlo.py:661: in __init__
    VFile.__init__(self, fname, ifname, ifile, ofname, ofile)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <montecarlo.InpFile object at 0x00000242E7EE4DD0>
fname = 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-justice\\Mod92_MC-setup_Working-example\\i25.inp'
ifname = 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-justice\\Mod92_MC-setup_Working-example\\i25_mc0.inp'
ifile = None
ofname = 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-justice\\Mod92_MC-setup_Working-example\\i25_mc.inp'
ofile = None

    def __init__(self, fname=None, ifname=None, ifile=None, ofname=None, ofile=None):
        """
        Standard Call: VFile(f) where f is a string representing the base path
                E.g., "b.dat" which implies "b_mc0.dat" has inputs and "b_mc.dat" gets results

        Alternatives: VFile(ifname="b_mc0.dat", ofname="b_mc.dat")
            You explicitly name the input and output files.
                ifname and ofname, but not fname, can be any pathlike object,
                and may specify a full or relative path, not just a filename.

        VFile(ifile=if, ofile=of)
                Where if and of are stream or filelike objects for input and output.

        Options can be mixed and matched, file arguments are preferred, then i/ofnames,
                and finally fname.
        Note that if you do not use fname you must specify the _mc part yourself.
        """
        if fname:
                pref,ext = fname.split('.')
                if ifname is None:
                        ifname = pref + '_mc0.' + ext
                if ofname is None:
                        ofname = pref + '_mc.' + ext
        self.ifname = ifname
        self.ofname = ofname
        if ifile:
                self.ifile = ifile
        elif ifname:
>               self.ifile = open(self.ifname, "rt")
                   ^^^^^^^^^^^^^^^^^^^^^^^
E     FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-justice\\Mod92_MC-setup_Working-example\\i25_mc0.inp'

bin\python\montecarlo.py:283: FileNotFoundError
=========================== short test summary info ===========================
FAILED py_tests/test_monte.py::test_inp - FileNotFoundError: [Errno 2] No suc...
========================= 1 failed, 5 passed in 1.92s =========================
Finished running tests!