Fix error detected by existing tests when using NumPy 2.0+
Here was the test result before the change.  The first failure in test_inp() is ongoing;
it is the second, in test_dat() that is new with NumPy 2.0+.

(pyenv) PS C:\Users\rdboylan\Documents\KBD\mccli-Iss24> python -m pytest
====================================================== test session starts =======================================================
platform win32 -- Python 3.11.5, pytest-8.4.2, pluggy-1.6.0
rootdir: C:\Users\rdboylan\Documents\KBD\mccli-Iss24
plugins: cov-7.0.0
collected 6 items

py_tests\test_monte.py F..F.                                                                                                [ 83%]
py_tests\test_sum_results.py .                                                                                              [100%]

============================================================ FAILURES ============================================================
____________________________________________________________ test_inp ____________________________________________________________

    def test_inp():
        # currently mostly used to see if montecarlo module loaded
        # it fails because input files are missing
>       inp = InpFile(str(rootDir / "Mod92_MC-setup_Working-example" / "i25"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

py_tests\test_monte.py:44:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bin\python\montecarlo.py:661: in __init__
    VFile.__init__(self, fname, ifname, ifile, ofname, ofile)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <montecarlo.InpFile object at 0x000002C5289963D0>
fname = 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-Iss24\\Mod92_MC-setup_Working-example\\i25.inp'
ifname = 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-Iss24\\Mod92_MC-setup_Working-example\\i25_mc0.inp', ifile = None
ofname = 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-Iss24\\Mod92_MC-setup_Working-example\\i25_mc.inp', ofile = None

    def __init__(self, fname=None, ifname=None, ifile=None, ofname=None, ofile=None):
        """
        Standard Call: VFile(f) where f is a string representing the base path
                E.g., "b.dat" which implies "b_mc0.dat" has inputs and "b_mc.dat" gets results

        Alternatives: VFile(ifname="b_mc0.dat", ofname="b_mc.dat")
            You explicitly name the input and output files.
                ifname and ofname, but not fname, can be any pathlike object,
                and may specify a full or relative path, not just a filename.

        VFile(ifile=if, ofile=of)
                Where if and of are stream or filelike objects for input and output.

        Options can be mixed and matched, file arguments are preferred, then i/ofnames,
                and finally fname.
        Note that if you do not use fname you must specify the _mc part yourself.
        """
        if fname:
                pref,ext = fname.split('.')
                if ifname is None:
                        ifname = pref + '_mc0.' + ext
                if ofname is None:
                        ofname = pref + '_mc.' + ext
        self.ifname = ifname
        self.ofname = ofname
        if ifile:
                self.ifile = ifile
        elif ifname:
>               self.ifile = open(self.ifname, "rt")
                   ^^^^^^^^^^^^^^^^^^^^^^^
E     FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-Iss24\\Mod92_MC-setup_Working-example\\i25_mc0.inp'

bin\python\montecarlo.py:283: FileNotFoundError
____________________________________________________________ test_dat ____________________________________________________________

    def test_dat():
        "test DatFile and SDFile generation of random numbers"
        RG = myRNG(4)
        input_data = get_input_data(ifname = testDir / 'MC' / 'inputs' / 'input_data.json')
        dat_files = input_data['dat_files']
        for datfiledata in dat_files:
            datfile = DatFile(datfiledata, RG,
                ifname = testDir / 'modfile' / (datfiledata['filename'] + '_mc0.dat'),
                ofname = testDir / 'modfile' / (datfiledata['filename'] + '_mc.dat'),
                sdifname = testDir / 'modfile' / (datfiledata['filename'] + '_sd.dat'))
>           datfile.vary()

py_tests\test_monte.py:109:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bin\python\montecarlo.py:305: in vary
    self.vary_line(line_num)
bin\python\montecarlo.py:372: in vary_line
    varied = self.sdfile.get_variation(line_num)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin\python\montecarlo.py:612: in get_variation
    return self._do_line(line_num)
           ^^^^^^^^^^^^^^^^^^^^^^^
bin\python\montecarlo.py:627: in vary_by_row
    return self._do_dist(rnd, means, sds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <montecarlo.SDFile object at 0x000002C52838E250>, q = 0.9890496507435015
means = array([ 7784.,  8612.,  9774., 10525., 10252.,  7603.]), sds = array([103.,  69.,  63.,  66.,  76., 103.])

    def _correlated_lognormal(self, q, means, sds):
        """Return <np.array> of correlated or uncorrelated log-normals.

        q are the quantiles to use.  If None, generate independent random variables.

        Each individual element has mean and sd as given in input vectors.
        q must either be the same size as those vectors or a single number.

        The input means and sds refer to the lognormal variable, not to
        the related normal variable.  This function derives appropriate
        parameters for the lognormal parameterized in terms of mu and
        sigma, which do refer to the related normal variable.
        """
        # convert from lists, which don't support math
        means = np.array(means)
        sds = np.array(sds)
        # mu and sigma may have fewer elements than means and sds
        # since they are only returned for rows with valid means and sds
        mu, sigma = mean_to_native("lognormal", means, sds)
        res = np.empty_like(means)
        mask = (sds>0.0)  # must be sds, not sigma
        # scipy docs say if log(Y) has mean mu and sd sigma then
        # use s = sigma and scale = exp(mu)
        if q is None:
                res[mask] = self.RG.lognormal(mu, sigma)
        else:
>               q0 = np.array(q, copy=False)  # q might be a single number
           ^^^^^^^^^^^^^^^^^^^^^^^
E     ValueError: Unable to avoid copy while creating an array as requested.
E     If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
E     For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

bin\python\montecarlo.py:556: ValueError
==================================================== short test summary info =====================================================
FAILED py_tests/test_monte.py::test_inp - FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-Iss24\\Mod92_MC-setup_Work...
FAILED py_tests/test_monte.py::test_dat - ValueError: Unable to avoid copy while creating an array as requested.
================================================== 2 failed, 4 passed in 17.02s ==================================================
(pyenv) PS C:\Users\rdboylan\Documents\KBD\mccli-Iss24> python -m pip list
Package         Version
--------------- -----------
colorama        0.4.6
contourpy       1.3.3
coverage        7.11.0
cycler          0.12.1
debugpy         1.8.17
fonttools       4.60.1
iniconfig       2.3.0
kiwisolver      1.4.9
matplotlib      3.10.7
numpy           2.3.4
packaging       25.0
pandas          2.3.3
pillow          12.0.0
pip             25.3
pluggy          1.6.0
Pygments        2.19.2
pyparsing       3.2.5
pytest          8.4.2
pytest-cov      7.0.0
python-dateutil 2.9.0.post0
pytz            2025.2
scipy           1.16.3
setuptools      65.5.0
six             1.17.0
tzdata          2025.2