Update node package dependencies to avoid nasty problem.
Attempting to npm install or update with the old version failed with lots of nasty errors
about failing to delete directories (EPERM) and failing to rebuild better-sqlite3 from source.

To get this I deleted package-lock.json and then did `npm install colors`.  Clearly this
installed everything.  I'm not sure if that means it stuck scripts in bin somewhere; I don't see them
in node_modules/.bin/.

PS C:\Users\rdboylan\Documents\KBD> git clone mccli-HF mccli-HF3
Cloning into 'mccli-HF3'...
done.
PS C:\Users\rdboylan\Documents\KBD> cd .\mccli-HF3\
PS C:\Users\rdboylan\Documents\KBD\mccli-HF3> dir

    Directory: C:\Users\rdboylan\Documents\KBD\mccli-HF3

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/16/2025  11:40 AM                .vs
d-----        1/16/2025  11:40 AM                .vscode
d-----        1/16/2025  11:40 AM                bin
d-----        1/16/2025  11:40 AM                data
d-----        1/16/2025  11:40 AM                doc
d-----        1/16/2025  11:40 AM                master
d-----        1/16/2025  11:40 AM                obj
d-----        1/16/2025  11:40 AM                py_tests
d-----        1/16/2025  11:40 AM                __tests__
-a----        1/16/2025  11:40 AM            342 .gitignore
-a----        1/16/2025  11:40 AM           4663 ChangeLog.md
-a----        1/16/2025  11:40 AM          55398 installations.txt
-a----        1/16/2025  11:40 AM           4451 mccli.njsproj
-a----        1/16/2025  11:40 AM           1322 mccli.sln
-a----        1/16/2025  11:40 AM         294711 package-lock.json
-a----        1/16/2025  11:40 AM           1399 package.json
-a----        1/16/2025  11:40 AM          20596 README.md
-a----        1/16/2025  11:40 AM            584 requirements-freeze.txt
-a----        1/16/2025  11:40 AM            604 requirements.txt

PS C:\Users\rdboylan\Documents\KBD\mccli-HF3> npm root
C:\Users\rdboylan\Documents\KBD\mccli-HF3\node_modules
PS C:\Users\rdboylan\Documents\KBD\mccli-HF3> del .\package-lock.json
PS C:\Users\rdboylan\Documents\KBD\mccli-HF3> npm root
C:\Users\rdboylan\Documents\KBD\mccli-HF3\node_modules
PS C:\Users\rdboylan\Documents\KBD\mccli-HF3> npm install colors
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 350 packages, and audited 351 packages in 39s

47 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\rdboylan\Documents\KBD\mccli-HF3> npm list
@ecfairle/mccli@3.3.2 C:\Users\rdboylan\Documents\KBD\mccli-HF3
+-- @types/better-sqlite3@7.6.12
+-- better-sqlite3@9.6.0
+-- colors@1.4.0
+-- fs-extra@11.3.0
+-- fs@0.0.1-security
+-- inquirer@8.2.6
+-- jest@29.7.0
+-- n-readlines@1.0.3
+-- path@0.12.7
+-- progress@2.0.3
+-- shelljs@0.8.5
+-- single-line-log@1.1.2
`-- yargs@17.7.2

PS C:\Users\rdboylan\Documents\KBD\mccli-HF3> git branch
* HF
PS C:\Users\rdboylan\Documents\KBD\mccli-HF3> node -v
v22.13.0
PS C:\Users\rdboylan\Documents\KBD\mccli-HF3> npm -v
11.0.0

Here's the way things were:

Transcript started, output file is C:\Users\rdboylan\Documents\PowerShell_transcript.EB-WS-12.AxusXkih.20250109161922.txt
PS C:\Users\rdboylan> date; node -v

Thursday, January 9, 2025 4:19:28 PM
v22.13.0

PS C:\Users\rdboylan> npm -v
10.9.2
PS C:\Users\rdboylan> npm install npm@latest -g

added 1 package in 10s

24 packages are looking for funding
  run `npm fund` for details
PS C:\Users\rdboylan> npm -v
11.0.0
PS C:\Users\rdboylan> cd .\Documents\KBD\mccli-HF\
PS C:\Users\rdboylan\Documents\KBD\mccli-HF> Remove-Item .\node_modules -Recurse
PS C:\Users\rdboylan\Documents\KBD\mccli-HF> date; npm install colors fs fs-extra inquirer@^8.0.0 path progress shelljs single-line-log yargs

Thursday, January 9, 2025 4:22:27 PM
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     '\\\\?\\C:\\Users\\rdboylan\\Documents\\KBD\\mccli-HF\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\@types\no
de'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-HF\\node_modules\\@types\\node'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     '\\\\?\\C:\\Users\\rdboylan\\Documents\\KBD\\mccli-HF\\node_modules\\rxjs',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\rxjs\dist
\cjs\internal'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-HF\\node_modules\\rxjs\\dist\\cjs\\internal'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     '\\\\?\\C:\\Users\\rdboylan\\Documents\\KBD\\mccli-HF\\node_modules\\better-sqlite3',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\better-sq
lite3\build\deps'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-HF\\node_modules\\better-sqlite3\\build\\deps'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\better-sqlite3
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild --release
npm error Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm error   copy_builtin_sqlite3
npm error   sqlite3.c
npm error   win_delay_load_hook.cc
npm error   sqlite3.vcxproj -> C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\better-sqlite3\build\Release\\sqlite3.lib
npm error cl : command line warning D9025: overriding '/std:c++20' with '/std:c++17' [C:\Users\rdboylan\Documents\KBD\mccli-HF\node
_modules\better-sqlite3\build\better_sqlite3.vcxproj]
npm error   better_sqlite3.cpp
npm error C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\better-sqlite3\build\src\util\macros.lzz(150,33): error C2664: 'voi
d v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>,v8::AccessorGetterCallback,v8::AccessorSetterCallback,v8::Local<v8::Value>,
v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)': cannot convert argument 5 from 'v8::AccessControl' to 'v8::PropertyA
ttribute' [C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
npm error C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\better-sqlite3\build\src\util\macros.lzz(155,36): message : Convers
ion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) [C:\Users\rdboylan\Documents\K
BD\mccli-HF\node_modules\better-sqlite3\build\better_sqlite3.vcxproj]
npm error C:\Users\rdboylan\AppData\Local\node-gyp\Cache\22.13.0\include\node\v8-template.h(1049,8): message : see declaration of '
v8::ObjectTemplate::SetAccessor' [C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\better-sqlite3\build\better_sqlite3.vcxproj
]
npm error   test_extension.c
npm error   win_delay_load_hook.cc
npm error      Creating library C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\better-sqlite3\build\Release\test_extension.l
ib and object C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\better-sqlite3\build\Release\test_extension.exp
npm error   Generating code
npm error   Previous IPDB not found, fall back to full compilation.
npm error   All 3 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
npm error   Finished generating code
npm error   test_extension.vcxproj -> C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\better-sqlite3\build\Release\\test_exte
nsion.node
npm error prebuild-install warn install No prebuilt binaries found (target=22.13.0 runtime=node arch=x64 libc= platform=win32)
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@11.0.0
npm error gyp info using node@22.13.0 | win32 | x64
npm error gyp info find Python using Python version 3.12.4 found at "C:\Program Files\Python312\python.exe"
npm error gyp http GET https://nodejs.org/download/release/v22.13.0/node-v22.13.0-headers.tar.gz
npm error gyp http 200 https://nodejs.org/download/release/v22.13.0/node-v22.13.0-headers.tar.gz
npm error gyp http GET https://nodejs.org/download/release/v22.13.0/SHASUMS256.txt
npm error gyp http GET https://nodejs.org/download/release/v22.13.0/win-x64/node.lib
npm error gyp http 200 https://nodejs.org/download/release/v22.13.0/SHASUMS256.txt
npm error gyp http 200 https://nodejs.org/download/release/v22.13.0/win-x64/node.lib
npm error gyp info find VS using VS2019 (16.11.35425.106) found at:
npm error gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
npm error gyp info find VS run with --verbose for detailed information
npm error gyp info spawn C:\Program Files\Python312\python.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'C:\\Users\\rdboylan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main
.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'msvs',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-HF\\node_modules\\better-sqlite3\\build\\config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\rdboylan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args 'C:\\Users\\rdboylan\\AppData\\Local\\node-gyp\\Cache\\22.13.0\\include\\node\\common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=C:\\Users\\rdboylan\\AppData\\Local\\node-gyp\\Cache\\22.13.0',
npm error gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\rdboylan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp
',
npm error gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\rdboylan\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\22.13.0\\\\<(tar
get_arch)\\\\node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=C:\\Users\\rdboylan\\Documents\\KBD\\mccli-HF\\node_modules\\better-sqlite3',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'C:\\Users\\rdboylan\\Documents\\KBD\\mccli-HF\\node_modules\\better-sqlite3\\build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
npm error gyp info spawn args [
npm error gyp info spawn args 'build\\binding.sln',
npm error gyp info spawn args '/clp:Verbosity=minimal',
npm error gyp info spawn args '/nologo',
npm error gyp info spawn args '/p:Configuration=Release;Platform=x64'
npm error gyp info spawn args ]
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe` fa
iled with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\rdboylan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\
lib\build.js:216:23)
npm error gyp ERR! stack at ChildProcess.emit (node:events:524:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm error gyp ERR! System Windows_NT 10.0.17763
npm error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rdboylan\\AppData\\Roaming\\npm\\node_modules\\npm\\no
de_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
npm error gyp ERR! cwd C:\Users\rdboylan\Documents\KBD\mccli-HF\node_modules\better-sqlite3
npm error gyp ERR! node -v v22.13.0
npm error gyp ERR! node-gyp -v v11.0.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: C:\Users\rdboylan\AppData\Local\npm-cache\_logs\2025-01-10T00_22_27_591Z-debu
g-0.log