montecarlo.py allow override of default files and record improved understanding of how groups work in Notes.md and comments.
TRANSITION IS INCOMPLETE AND UNTESTED.
I've focused on things needed for InpFile, namely VFile, InpFile, Effects and the read_lines function.
So DatFile and SDFile still to go.

The directory separator was hardcoded, inconsistently, and I have eliminated some of that
by using the Path / operator.

This exposes that some of the code hit by InpFile (in Component) is not compatible
with the latest NumPy.  Stack trace at bottom; .state is no longer defined from RandomGenerator.

To Do:
Fix numpy compatibility (really not part of this issue, but still...)
Test existing code
Extend new file handling to DatFile and friends.
Consolidate handling of random numbers between DatFile and InpFile (really, Components), favoring methods of former to assure correlation.
Consider adding truncated, not censored, distributions.
Consider lognormal with original parameterization.

    component = Component(line)
  File "J:\source\repos\mccli\bin\python\montecarlo.py", line 723, in __init__
    if self.set_group(parts[0]):
  File "J:\source\repos\mccli\bin\python\montecarlo.py", line 756, in set_group
    self.group_state[self.group] = RG.state
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'state'