Create a test to reproduce the problem in Issue #24.
This now fails, appropriately since the problem isn't fixed yet.

I encountered problems running the test until I messed with
file permissions.  Git seems unlikely to preserve them. The
last paragraph in Iss24/ReadMe.md gives details.  It probably
needs more prominent placement.

Here's the tail end of the test:
>       assert nLines in (14, 15)  # 15 allows for the blank line at the end
        ^^^^^^^^^^^^^^^^^^^^^^^^^
E       assert 19 in (14, 15)

py_tests\test_sum_results.py:37: AssertionError
=========================== short test summary info ===========================
FAILED py_tests/test_sum_results.py::test_shared_prefix - assert 19 in (14, 15)
============================== 1 failed in 0.92s ==============================
Finished running tests!