Allowing the code to execute shows node is unhappy in this environment because it knows it has a different output stream type.  Perhaps binary mode for subprocess would have better luck?
TypeError: process.stdout.clearLine is not a function
    at error (C:\Users\rdboylan\Documents\KBD\mccli-parallel\bin\js
\runSims.js:15:17)
    at module.exports [as handler] (C:\Users\rdboylan\Documents\KBD
\mccli-parallel\bin\js\runSims.js:200:3)
    at C:\Users\rdboylan\Documents\KBD\mccli-repeatable\node_module
s\yargs\build\index.cjs:1:8993
    at j (C:\Users\rdboylan\Documents\KBD\mccli-repeatable\node_mod
ules\yargs\build\index.cjs:1:4956)
    at _.handleValidationAndGetResult (C:\Users\rdboylan\Documents\
KBD\mccli-repeatable\node_modules\yargs\build\index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (C:\Users\rdboylan\Documents\K
BD\mccli-repeatable\node_modules\yargs\build\index.cjs:1:9604)
    at _.runCommand (C:\Users\rdboylan\Documents\KBD\mccli-repeatab
le\node_modules\yargs\build\index.cjs:1:7231)
    at [runYargsParserAndExecuteCommands] (C:\Users\rdboylan\Docume
nts\KBD\mccli-repeatable\node_modules\yargs\build\index.cjs:1:58539
)
    at te.parse (C:\Users\rdboylan\Documents\KBD\mccli-repeatable\n
ode_modules\yargs\build\index.cjs:1:40478)
    at te.get [as argv] (C:\Users\rdboylan\Documents\KBD\mccli-repe
atable\node_modules\yargs\build\index.cjs:1:62028)

Node.js v22.15.1
Done with status None.